verifyInputs function and one test. Test for strangle spreads.
antoncoding/grappa pull request #146
Opened 2022-11-09 00:51 UTC by hashnoteleo

base verify inputs with one test and test for strangle spread. Expect more tests tomorrow am.

2022-11-09 04:03 UTC, dsshap requested changes

2022-11-09 04:03 UTC, dsshap commented on src/test/unit-tests/full-margin-engine-v2/FullMarginMathV2.t.sol
> +    function testVerifyInputs1() public {
Lets add a few negative test cases

2022-11-09 04:03 UTC, dsshap commented on src/test/unit-tests/full-margin-engine-v2/FullMarginMathV2.t.sol
> +    function testStrangleSpread() public {
Yay!

2022-11-09 11:52 UTC, hashnoteleo commented on src/test/unit-tests/full-margin-engine-v2/FullMarginMathV2.t.sol
> +    function testVerifyInputs1() public {
done

2022-11-09 11:53 UTC, hashnoteleo commented on src/core/engines/full-margin-v2/FullMarginMathV2.sol
> +    error FMMV2_InvalidZeroWeights();
Could go either way? At least one :). Made it singular.

2022-11-09 11:53 UTC, hashnoteleo commented on src/core/engines/full-margin-v2/FullMarginMathV2.sol
> +        // verifyInputs();
uncommented.

2022-11-09 11:54 UTC, hashnoteleo commented on src/core/engines/full-margin-v2/FullMarginMathV2.sol
> +        external pure returns (bool goodInputs)
Yea, i was torn whether to return or not. Removed it.

2022-11-09 22:30 UTC, dsshap commented on src/test/unit-tests/full-margin-engine-v2/FullMarginMathV2.t.sol
> +        vm.expectRevert();
Add the error selector so that is precise with what its looking for.

2022-11-09 22:30 UTC, dsshap commented on src/test/unit-tests/full-margin-engine-v2/FullMarginMathV2.t.sol
> +        vm.expectRevert();
same as above

2022-11-09 22:30 UTC, dsshap commented on src/test/unit-tests/full-margin-engine-v2/FullMarginMathV2.t.sol
> +        vm.expectRevert();
same as above

2022-11-09 22:30 UTC, dsshap commented on src/core/engines/full-margin-v2/FullMarginMathV2.sol
> +    error FMMV2_InvalidZeroWeight(int256[] weights);
remove `int256[] weights`

2022-11-09 22:30 UTC, dsshap commented on src/core/engines/full-margin-v2/FullMarginMathV2.sol
> +        view //pure
swap back for pure

2022-11-09 22:30 UTC, dsshap commented on src/core/engines/full-margin-v2/FullMarginMathV2.sol
> +        view //pure
same as above

2022-11-11 02:48 UTC, dsshap approved these changes

2022-11-11 02:48 UTC, merged